global.DefaultLang = "zh-CN"
global.SiteName = "None"
global.RegisterPath = "https://127.0.0.1/register.php"
global.CartPath = "https://127.0.0.1/cart.php"
global.APIPath = "https://127.0.0.1/modules/servers/V2raySocks/api.php"
global.ucKey = "oPajn1k2-jJanKn3k18bajdhaiYa_p"
global.licKey = "\$a4-mugb_qjOamj_fkaiznjaq2\$fmoz"